# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_file_cpp2 <- function(path) {
    .Call('_zdeviceR_read_file_cpp2', PACKAGE = 'zdeviceR', path)
}

